/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jframe;

public class JFrameLK extends javax.swing.JFrame {
           
    public JFrameLK() {
        initComponents();
        responsavel.setVisible(false);
        nresp.setVisible(false);
        impcadas.setVisible(false);
        impcadas.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        verde = new javax.swing.JPanel();
        branco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        serie = new javax.swing.JTextField();
        dnascimento = new javax.swing.JTextField();
        responsavel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nresp = new javax.swing.JLabel();
        informatica = new javax.swing.JRadioButton();
        eletrotecnica = new javax.swing.JRadioButton();
        quimica = new javax.swing.JRadioButton();
        geologia = new javax.swing.JRadioButton();
        cadastrar = new javax.swing.JButton();
        idade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        impcadas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        respimpri = new javax.swing.JLabel();
        serieimprimi = new javax.swing.JLabel();
        cursoimprimir = new javax.swing.JLabel();
        nascimprimir = new javax.swing.JLabel();
        nomeimprimir = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idadimprimir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        verde.setBackground(new java.awt.Color(0, 102, 102));
        verde.setPreferredSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout verdeLayout = new javax.swing.GroupLayout(verde);
        verde.setLayout(verdeLayout);
        verdeLayout.setHorizontalGroup(
            verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        verdeLayout.setVerticalGroup(
            verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(verde);
        verde.setBounds(0, 0, 380, 500);

        branco.setMinimumSize(new java.awt.Dimension(400, 500));
        branco.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("CADASTRO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("NOME:");

        nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        serie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dnascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dnascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnascimentoActionPerformed(evt);
            }
        });

        responsavel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        responsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsavelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("DATA DE NASCIMENTO:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("CURSO:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("SÉRIE:");

        nresp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nresp.setText("NOME DO RESPONSÁVEL:");

        buttonGroup1.add(informatica);
        informatica.setText("INFORMÁTICA");

        buttonGroup1.add(eletrotecnica);
        eletrotecnica.setText("ELETROTÉCNICA");

        buttonGroup1.add(quimica);
        quimica.setText("QUÍMICA");

        buttonGroup1.add(geologia);
        geologia.setText("GEOLOGIA");

        cadastrar.setBackground(new java.awt.Color(0, 102, 102));
        cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        idade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("IDADE:");

        javax.swing.GroupLayout brancoLayout = new javax.swing.GroupLayout(branco);
        branco.setLayout(brancoLayout);
        brancoLayout.setHorizontalGroup(
            brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brancoLayout.createSequentialGroup()
                .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(brancoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(informatica)
                            .addComponent(eletrotecnica))
                        .addGap(44, 44, 44)
                        .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quimica)
                            .addComponent(geologia)))
                    .addGroup(brancoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(brancoLayout.createSequentialGroup()
                                .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(dnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nresp)
                            .addComponent(jLabel2)
                            .addGroup(brancoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6))
                            .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(brancoLayout.createSequentialGroup()
                .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(brancoLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(brancoLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        brancoLayout.setVerticalGroup(
            brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brancoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(informatica)
                    .addComponent(quimica))
                .addGap(18, 18, 18)
                .addGroup(brancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eletrotecnica)
                    .addComponent(geologia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nresp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel1.add(branco);
        branco.setBounds(380, 0, 420, 500);

        impcadas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("NOME:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("DATA DE NASCIMENTO:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("CURSO:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("SÉRIE:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("NOME DO RESPONSÁVEL:");

        respimpri.setText("jLabel12");

        serieimprimi.setText("jLabel13");

        cursoimprimir.setText("jLabel14");

        nascimprimir.setText("jLabel15");

        nomeimprimir.setText("jLabel16");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("IDADE:");

        idadimprimir.setText("jLabel13");

        javax.swing.GroupLayout impcadasLayout = new javax.swing.GroupLayout(impcadas);
        impcadas.setLayout(impcadasLayout);
        impcadasLayout.setHorizontalGroup(
            impcadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(impcadasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(impcadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(impcadasLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeimprimir))
                    .addGroup(impcadasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nascimprimir))
                    .addGroup(impcadasLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cursoimprimir))
                    .addGroup(impcadasLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serieimprimi))
                    .addGroup(impcadasLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(respimpri))
                    .addGroup(impcadasLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idadimprimir)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        impcadasLayout.setVerticalGroup(
            impcadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(impcadasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(impcadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nomeimprimir))
                .addGap(18, 18, 18)
                .addGroup(impcadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nascimprimir))
                .addGap(20, 20, 20)
                .addGroup(impcadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cursoimprimir))
                .addGap(20, 20, 20)
                .addGroup(impcadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(serieimprimi))
                .addGap(20, 20, 20)
                .addGroup(impcadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(respimpri))
                .addGap(20, 20, 20)
                .addGroup(impcadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(idadimprimir))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(impcadas);
        impcadas.setBounds(380, 500, 420, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("cadastrar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dnascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnascimentoActionPerformed

    private void responsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_responsavelActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        String name = nome.getText();
        nomeimprimir.setText(name);
        
        String data = dnascimento.getText();
        nascimprimir.setText(data);
        
        int year = Integer.parseInt(idade.getText());
        idadimprimir.setText(Integer.toString(year));
        
        String corso;
        if(eletrotecnica.isSelected()){
            corso = eletrotecnica.getText();
            cursoimprimir.setText(corso);
        }
        if(informatica.isSelected()){
            corso = informatica.getText();
            cursoimprimir.setText(corso);
        }
        if(quimica.isSelected()){
            corso = quimica.getText();
            cursoimprimir.setText(corso);
        }
        if(geologia.isSelected()){
            corso = geologia.getText();
            cursoimprimir.setText(corso);
        }
        
        branco.setVisible(false);
        verde.setVisible(false);
        impcadas.setVisible(true);
        
        String rep = responsavel.getText();
        nresp.setVisible(true);
        respimpri.setText(rep);
        respimpri.setVisible(true);
 
        if(year <18){
            nresp.setVisible(true);
            responsavel.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarActionPerformed

    private void idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeActionPerformed
        int ida =Integer.parseInt(idade.getText());
        if(ida<18){
            nresp.setVisible(true);
            responsavel.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel branco;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel cursoimprimir;
    private javax.swing.JTextField dnascimento;
    private javax.swing.JRadioButton eletrotecnica;
    private javax.swing.JRadioButton geologia;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel idadimprimir;
    private javax.swing.JPanel impcadas;
    private javax.swing.JRadioButton informatica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nascimprimir;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomeimprimir;
    private javax.swing.JLabel nresp;
    private javax.swing.JRadioButton quimica;
    private javax.swing.JLabel respimpri;
    private javax.swing.JTextField responsavel;
    private javax.swing.JTextField serie;
    private javax.swing.JLabel serieimprimi;
    private javax.swing.JPanel verde;
    // End of variables declaration//GEN-END:variables
}
